trigger:
  branches:
    include:
      - dev

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: templates/install-dependencies.yaml

  # Scripts for running all tests in a file and to run tests based on test case name (integration testing)
  - script: |
      robot --output results/logs/output_kim_test.xml --log results/logs/log_kim_test.html --report results/logs/report_kim_test.html tests/kim-test-cases.robot
    displayName: 'Run Test File "Kim-test-cases"'
    continueOnError: true

  - script: |
      robot --output results/logs/output_generic_test.xml --log results/logs/log_generic_test.html --report results/logs/report_generic_test.html tests/generic.robot
    displayName: 'Run Test File "Generic"'
    continueOnError: true

  - script: |
      robot --output results/logs/output_snala-kalle_test.xml --log results/logs/log_snala-kalle_test.html --report results/logs/report_snala-kalle_test.html tests/snåla-kalle.robot
    displayName: 'Run Test File "snala-kalle"'
    continueOnError: true

  # Publish the Robot Framework reports as pipeline artifacts.
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/results/logs/'
      artifactName: 'robot-reports-develop'
    displayName: 'Publish Robot Framework Reports'


