trigger:
  - feature/*

pr: none  # disabling the trigger during PR, trying to create a dedicated PR merge pipeline --TT

pool:
  vmImage: 'ubuntu-latest'

steps:

  - template: templates/install-dependencies.yaml

  - script: |
      robot --include new-feature --output results/logs/output_feature_test.xml --log results/logs/log_feature_test.html --report results/logs/report_feature_test.html tests/
    displayName: 'Run Tests tagged with new-feature'
    continueOnError: true
    env:
      BROWSER: chrome
      CHROME_VERSION: 132

  # Publish the Robot Framework reports as pipeline artifacts.
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/results/logs/'
      artifactName: 'robot-reports-feature'
    displayName: 'Publish Robot Framework Reports'


